version: "3.3"

services:

  server:
    build:
      context: .
    image: moleculer-demo
    env_file: docker-compose.env
    environment:
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal
    ports:
      - "3000:3000"
    expose:
      - "3000"

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

networks:
  internal:

volumes:
  data:
