name: CI/CD to Docker Hub

on:
  push:
    branches: [ main, bugfix/cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --ignore-scripts
      - name: Build and Test App
        run: |
          npm install --ignore-scripts
          npm run build
          npm test a
        working-directory: .

      - name: Setup ENV
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          IMAGE_NAME=ecse437.azurecr.io
          echo "IMAGE_TAG_NAME_SERVER=$IMAGE_NAME:${GIT_HASH}" >> $GITHUB_ENV

      - name: Install Docker Compose CLI
        run: >
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
      - uses: docker/login-action@v1.8.0
        with:
          registry: ecse437.azurecr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}
          login-server: ecse437.azurecr.io

      - name: Build and Push Docker Container
        run: |
          docker build -t $IMAGE_TAG_NAME_SERVER .
          docker push $IMAGE_TAG_NAME_SERVER

      - name: Create ACI Context
        run: docker context create aci --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group container --location useast acicontext
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
