name: Build on Main

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.0, 4.2, 4.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install --ignore-scripts
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
      - run: npm run integration
        env:
          CI: true
